# Reusable workflow consumed by ci.yml; used to share a single matrix across jobs.
on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
      python-version:
        required: true
        type: string
      poetry-version:
        required: true
        type: string

defaults:
  run:
    shell: bash

jobs:
  tests:
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/poetry-install
        with:
          python-version: ${{ inputs.python-version }}
          poetry-version: ${{ inputs.poetry-version }}

      - name: Run unit tests
        run: |
          poetry run pytest spotify_sync/tests