name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.11']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Poetry
        run: |
          pipx install poetry==1.8.4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
          cache-dependency-path: poetry.lock

      - name: Set Poetry environment
        run: |
          poetry env use ${{ matrix.python-version }}

      - name: Install project dependencies
        run: |
          poetry install --no-interaction --no-root

      - name: Code Quality
        run: poetry run black . --check

      - name: Unit Tests
        run: poetry run pytest spotify_sync/tests
